### ISSUE TITLE
Work with plotter and 2 motors

### ISSUE THREAD

**Issue by gabrielfedel** [lnls-sol/py4syn#10]
How can I use plotter with 1 counter and 2 motors?
Is it possible to use on axis a step counter or time counter?

**Comment by hhslepicka** [comment]
Hi @gabrielfedel , I'm not sure if I understood what you are asking.
Would you be able to provide an example (static image) of the plot that you want to create?
Is it a 3D Plot with X and Z as motors and the counter as Y?

**Comment by gabrielfedel** [comment]
Hi Hugo, I should make two issues...
I have a scan case where I have 2 motors and 1 counter, and I would like to make some useful plot.
One alternative could be a 3D plot, like you said, but I think the information isn't useful...

Another possibility is to x be the steps (if are 2 steps to one motor, and 3 to another, will be 6 steps) and y be the counter values... But I don't know if is possible to use a value on axis like this step counter,or a time counter ....

**Comment by hhslepicka** [comment]
@gabrielfedel so you are doing a mesh scan, right?
If I'm not wrong you can specify X as being 'points' and it will produce the result expected on the second case.

```
setX('points')
mesh(m1, 0, 1, 10, m2, 1, 2, 5, 1)
```

**Comment by hhslepicka** [comment]
@gabrielfedel Did it work?

**Comment by gabrielfedel** [comment]
In a first test no...
But I didn't have much time. I will perform more tests.

**Comment by hhslepicka** [comment]
I see... please provide the code that you are using so I can take a better
look at the problem.

**Comment by hhslepicka** [comment]
Hi @gabrielfedel, any news on the tests?

**Comment by gabrielfedel** [comment]
Hi, I remade some tests and work (using points). I think the problem is the place where plot is in my code (with a lot of other files). I will close the issue.

Thank you!

**Comment by hhslepicka** [comment]
That is great! Thanks for testing.
