### ISSUE TITLE
A way to redirect output

### ISSUE THREAD

**Issue by gabrielfedel** [lnls-sol/py4syn#12]
I'm implementing a gui and would like to print scan output on it, but I can't find a way. Is there some way to do this? 

Maybe the best option is to let a way to configure scan (and other methods) ouputs...

**Comment by hhslepicka** [comment]
Hi @gabrielfedel, for that you can create your own callback and subscribe to the scan running.
Please see: http://py4syn.readthedocs.io/en/latest/utils/utils_scan.html#callbacks, you can use a PostPointCallback.
Here is where we execute it: https://github.com/hhslepicka/py4syn/blob/master/py4syn/utils/scan.py#L1147.

One other option but this is more hacking into the deeps of Py4Syn is to overwrite the printAndPlot method at the Scan Object and do what you need to do: https://github.com/hhslepicka/py4syn/blob/master/py4syn/utils/scan.py#L967.

**Comment by gabrielfedel** [comment]
Ah great, I'm forgot the callbacks 
thanks!

**Comment by hhslepicka** [comment]
Great! :+1:
