### ISSUE TITLE
A "safe" way to stop a scan

### ISSUE THREAD

**Issue by gabrielfedel** [lnls-sol/py4syn#13]
I'm need to a way to stop a running scan from an gui, is there some safe way?

I thinking do something with prepointcallback (like set numberofpoints to 0, to finish scan main loop), but this not looks a good work around...

**Comment by hhslepicka** [comment]
Hi @gabrielfedel, please provide some code in order to make it easier to understand what you are doing in terms of launching the scan from the gui.

**Comment by gabrielfedel** [comment]
Here: https://gist.github.com/gabrielfedel/f6b5391a1d58f91c17637268014f8923
I tryied to put all important files.

It is a bit mess (I workin on a existent scan script -scan.py- that uses py4syn scan and configuration files)

I created scanGui.py (https://gist.github.com/gabrielfedel/f6b5391a1d58f91c17637268014f8923#file-scangui-py) to extend scan.py (https://gist.github.com/gabrielfedel/f6b5391a1d58f91c17637268014f8923#file-scan-py ) like a thread.

So I would like a way to interrupt the scan from window....

Thank you!

**Comment by hhslepicka** [comment]
I will take a look at it.

**Comment by hhslepicka** [comment]
@gabrielfedel Would you please test the new branch "**scan_pause_interrupt_resume**".
You can check by the diff that I added the following new methods to the Scan class:

**- Pause**
Pause the current scan before the next point.

**- Interrupt**
Interrupt the current scan, aka Kill the scan.

**- Resume**
Resume the scan from the last point if the scan was paused.

**- getState**
Return the current state of the scan (idle, paused, interrupted, error).

**- setPausePoolingRate**
Configure how long in seconds we will wait before checking the __paused flag again.

**- __check_pause_interrupt**
Check the flags __interrupted and __paused and execute the corresponding action.  

I tested this concept outside of py4syn with a small code and it works.
Please let me know if you find bugs or other issues.
I will create the PR for now as WIP (Work in Progress) while you run the tests. As soon as you get back to me we can merge it and have it all in the package.

Cheers!

**Comment by gabrielfedel** [comment]
Thank you Hugo!

I will take a look soon and return you a feedback!

Regards

**Comment by gabrielfedel** [comment]
@hhslepicka I'm trying to use the new methods, but I can't find a way to call them. 
I start the scan with scan wrapper, so how can I access the object Scan to call the methods?

**Comment by hhslepicka** [comment]
Hi @gabrielfedel,

This is the way to go:
'''
s=getScanData()['SCAN_OBJECT']
s.interrupt()
'''

**Comment by gabrielfedel** [comment]
Thank you! 

(
Just to register, the right way:
''' s=getScanData()['scan_object'] 
s.interrupt() '''
)

I fixed a small issue and submitted a new pull request. 
With this small correction everything is working very well!

**Comment by hhslepicka** [comment]
Thank you for testing and submitting the FIX for the bug.
