### ISSUE TITLE
timescan datafile empy

### ISSUE THREAD

**Issue by gabrielfedel** [lnls-sol/py4syn#26]
When use timescan, the data is saved to the file output?
Testing timescan the result file has only the header, without data collected:

#E 1494953412                 
#D Tue May 16 13:50:12 2017   
#C py4syn User = gabriel.fedel
#C0                           
#S 1 timescan(1, 0)           
#D Tue May 16 13:50:12 2017   
#N 1                          
#L ocean

**Comment by hhslepicka** [comment]
@gabrielfedel, it was supposed to save...
Would you mind to inform the command that you used for it?
Also, how are you stopping the timescan?
Are you using it from the python shell or something else?

**Comment by gabrielfedel** [comment]
Just to complete the issue, data result appears on shell, but aren't save to file.

I try on python shell, like this:

from py4syn.epics.OceanClass import OceanOpticsSpectrometer  
from py4syn.utils.counter import createCounter    
from py4syn.utils.scan import timescan, setOutput

ocean = OceanOpticsSpectrometer("ocean1",pv="SOL3:Ocean")           
createCounter("ocean", ocean)        
setOutput("/tmp/timeteste")

timescan(1, 0, 1)

----

Looking the code, I saw that timescan didn't use addScanParam (and scan and mesh uses), and __writeData use this information. Could be this the problem?

**Comment by hhslepicka** [comment]
@gabrielfedel, timescan has no need to addScanParam as it only needs CountTime, DelayTime and Repeat...

Was this performed in a new shell without any other code before?

**Comment by gabrielfedel** [comment]
Hum...Ok!

Yes, just this code.

**Comment by hhslepicka** [comment]
@gabrielfedel I was able to reproduce and fix the bug.
Thanks for reporting this one!

**Comment by gabrielfedel** [comment]
Great!
Thank you!
