### ISSUE TITLE
Plotter constructor is not compatible with plot() from py4syn.utils.scan.scan() function

### ISSUE THREAD

**Issue by marciodo** [lnls-sol/py4syn#6]
The plot function has this call to Plotter: 

p = Plotter("Plot", xlabel=XFIELD, ylabel=YFIELD, line_style="-", line_marker=".", line_color="blue", daemon=True)

But kwargs was commented out inside Plotter constructor: def **init**(self, title, daemon=True, priority=0):#, **kwargs) and a call to scan.plot() does not work.

**Comment by hhslepicka** [comment]
@marciodo This was a leftover from a refactor. Luckily until now no one had used this function.
I will submit a fix for this issue soon. Thanks!

**Comment by hhslepicka** [comment]
@marciodo The fix is available at master. I also fixed the documentation at the Plotter class in order represent the correct set of parameters.

**Comment by marciodo** [comment]
I tested and it seems it is ok, now.
