### ISSUE TITLE
Scan/Mesh 2 (or more) motors in a list of points

### ISSUE THREAD

**Issue by gabrielfedel** [lnls-sol/py4syn#9]
Is possible to perform a scan with two motors and pass what points each will go?
I would like to do a "zigzag" movement, and trying to solve with a list of points (step-by-step).

**Comment by hhslepicka** [comment]
@gabrielfedel it is possible.
The group ```start, end, steps``` can be replaced by ```list, steps```
The only constrain is that for the scan, the number of steps for the motors must be the same.
Please take a look at: http://py4syn.readthedocs.io/en/latest/utils/utils_scan.html#py4syn.utils.scan.mesh
and:
http://py4syn.readthedocs.io/en/latest/utils/utils_scan.html#py4syn.utils.scan.scan

**Comment by gabrielfedel** [comment]
I'm trying to make a scan with motors m1 and m2, on positions 1, 2, 3 and 4 for m1 and 4, 3, 2, 1 for m2. All measures with 1.0 acquisition time... I trying some like these:

scan('m1', [1,2,3,4],1, 'm2', [1,2,3,4],1)
scan('m1', [1,2,3,4],[1,1,1,1], 'm2', [1,2,3,4],[1,1,1,1])

But didn't work...

when you say list, steps, I imagine that list is the points (for each motor) and steps the step between each point, right?

**Comment by gabrielfedel** [comment]
Sorry @hhslepicka i found the way to do this. I was confuse with the two ways to use scan.

scan('m1', [1,2,3,4],'m2', [1,2,3,4],1)

**Comment by hhslepicka** [comment]
No problem @gabrielfedel in fact the documentation is a little confusing. I will work on that soon! ;)
Thanks for your input.

**Comment by gabrielfedel** [comment]
I will try to contribute a bit with this soon too (if is not a problem)

**Comment by hhslepicka** [comment]
Not a problem at all! All contribution is welcome! Thank you again!

**Comment by gabrielfedel** [comment]
@hhslepicka , I'm trying to make scan with 2 motors and a unique acquisition time

I'm trying some like this:
scan('m1', [1,2,3,4],'m2', [1,2,3,4],0.5)

(where 0.5 is the acquisition time for all points)

But didn't work. How could a do this? I need to indicate acquisition time for each point?

**Comment by hhslepicka** [comment]
Hi Gabriel,
If the acquisition time is a scalar it will be one for all the points as
you expected.
Would you mind to describe which counter you are using?
Do you receive any error message?

Please try the following:

getScanData()['scan_object'].getCountTime()

This should point to you the count time assigned to the scan that was last
executed.

**Comment by gabrielfedel** [comment]
Hi Hugo, 

The counter I'm using is dxp (that class I created), this could interfere on count time?

The result of getCountTime is 1 (I'm passing 0.5, but it is using default value 1).

**Comment by hhslepicka** [comment]
@gabrielfedel, just to confirm: Is the scan happening with both motors or just the first one?

**Comment by hhslepicka** [comment]
@gabrielfedel please try the following and let me know the result:
```
scan('m1', [1,2,3,4],'m2', [1,2,3,4], 4, 0.5)  # 4 is the number of steps.
print(getScanData()['scan_object'].getCountTime())
```

**Comment by gabrielfedel** [comment]
Hello Hugo, 

Yes, the scan happening with both motos.

Now Work! Using the number of steps. Thank you!

**Comment by hhslepicka** [comment]
The number of steps is a required parameter even when we use arrays. I will
come up with a solution on the argument parser to avoid this from happening.

Thanks again for the input.
